# Generated by Django 4.0.3 on 2022-04-05 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='donor_tlgrm_ru',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(default='', max_length=100, verbose_name='Домен донора')),
                ('url', models.CharField(default='', max_length=255, verbose_name='Основной URL')),
                ('LastUpdateData', models.DateTimeField(auto_now=True, verbose_name='Дата последнего обновления')),
            ],
        ),
    ]
