# Generated by Django 4.0.3 on 2022-04-06 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='donor_tlgrm_ru',
            options={'verbose_name': 'Донор tlgrm_ru', 'verbose_name_plural': 'Донор tlgrm_ru'},
        ),
        migrations.AlterField(
            model_name='donor_tlgrm_ru',
            name='domain',
            field=models.CharField(default='https://tlgrm.ru', max_length=100, verbose_name='Домен донора'),
        ),
        migrations.AlterField(
            model_name='donor_tlgrm_ru',
            name='url',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Основной URL'),
        ),
    ]
