# Generated by Django 4.0.3 on 2022-04-06 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0002_alter_donor_tlgrm_ru_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor_tlgrm_ru',
            name='LastUpdateData',
            field=models.DateTimeField(verbose_name='Дата последнего обновления'),
        ),
    ]
