# Generated by Django 4.0.3 on 2022-04-06 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0006_alter_donor_tlgrm_ru_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor_tlgrm_ru',
            name='LastUpdateData',
            field=models.DateTimeField(blank=True, default='', null=True, verbose_name='Дата последнего обновления'),
        ),
    ]
