# Generated by Django 4.0.3 on 2022-04-06 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0011_alter_donor_tlgrm_ru_lastupdatedata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor_tlgrm_ru',
            name='url',
            field=models.CharField(default='', max_length=255, null=True, verbose_name='Основной URL'),
        ),
    ]
