# Generated by Django 3.2.12 on 2022-04-13 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriesMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donor_categories_name', models.CharField(default='', max_length=255, verbose_name='Название категории у донора')),
                ('keywords', models.CharField(blank=True, default=None, max_length=255, verbose_name='Ключевые слова категории')),
            ],
            options={
                'verbose_name': 'Соответствие категорий',
                'verbose_name_plural': 'Соответствие категорий',
            },
        ),
        migrations.CreateModel(
            name='CatName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=30, verbose_name='Название категорий')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='TgmChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Наименование канала')),
                ('tgmlink', models.CharField(default='', max_length=255, verbose_name='Cсылка на телеграмм')),
                ('description', models.CharField(default='', max_length=255, verbose_name='Описание канала')),
                ('subs', models.IntegerField(blank=True, default='', null=True, verbose_name='Кол-во подписчиков')),
                ('logo', models.ImageField(blank=True, upload_to='channel_logo/', verbose_name='Лого канала')),
                ('categories_match', models.ManyToManyField(to='tgm_channel.CategoriesMatch')),
            ],
            options={
                'verbose_name': 'Канал',
                'verbose_name_plural': 'Каналы',
            },
        ),
        migrations.AddField(
            model_name='categoriesmatch',
            name='name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tgm_channel.catname'),
        ),
    ]
