# Generated by Django 4.0.3 on 2022-04-05 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgm_channel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='keywords',
            field=models.CharField(default='', max_length=255, verbose_name='Ключевые слова категории'),
        ),
        migrations.AlterField(
            model_name='categories',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Название категорий'),
        ),
        migrations.AlterField(
            model_name='tgmchannel',
            name='logo',
            field=models.ImageField(blank=True, upload_to='channel_logo/', verbose_name='Лого канала'),
        ),
    ]
