# Generated by Django 4.0.3 on 2022-04-06 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgm_channel', '0002_categories_keywords_alter_categories_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='donor_categories_name',
            field=models.CharField(default='', max_length=255, verbose_name='Название категории у донора'),
        ),
    ]
