# Generated by Django 4.0.3 on 2022-04-06 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgm_channel', '0003_categories_donor_categories_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categories',
            name='TgmChannel',
        ),
        migrations.AddField(
            model_name='tgmchannel',
            name='DonorCategori',
            field=models.ManyToManyField(to='tgm_channel.categories'),
        ),
    ]
