# Generated by Django 4.0.3 on 2022-04-07 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgm_channel', '0005_rename_donorcategori_tgmchannel_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='keywords',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Ключевые слова категории'),
        ),
        migrations.AlterField(
            model_name='categories',
            name='name',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='Название категорий'),
        ),
    ]
