# Generated by Django 3.2.12 on 2022-04-13 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tgm_channel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriesmatch',
            name='name_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tgm_channel.catname'),
        ),
        migrations.AlterField(
            model_name='categoriesmatch',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=30, verbose_name='Название категорий'),
        ),
    ]
