# Generated by Django 3.2.12 on 2022-04-15 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tgm_channel', '0002_auto_20220413_1513'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoriesmatch',
            name='name_id',
        ),
    ]
