# Generated by Django 3.2.12 on 2022-04-15 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tgm_channel', '0003_remove_categoriesmatch_name_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='tgmchannel',
            name='cat_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tgm_channel.catname'),
        ),
    ]
