# Generated by Django 3.2.12 on 2022-04-15 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tgm_channel', '0004_tgmchannel_cat_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tgmchannel',
            name='cat_id',
        ),
    ]
