# Generated by Django 3.2.12 on 2022-04-16 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgm_channel', '0006_categoriesmatch_name_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tgmchannel',
            name='categories_match',
            field=models.ManyToManyField(related_name='cat', to='tgm_channel.CategoriesMatch'),
        ),
    ]
