# Generated by Django 3.2.12 on 2022-04-24 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgm_channel', '0007_alter_tgmchannel_categories_match'),
    ]

    operations = [
        migrations.AddField(
            model_name='tgmchannel',
            name='LastUpdate',
            field=models.DateField(default='1900-01-01', verbose_name='Дата последнего обновления'),
        ),
        migrations.AddField(
            model_name='tgmchannel',
            name='active',
            field=models.BooleanField(blank=True, default=False, verbose_name='Активен ли канал'),
        ),
        migrations.AlterField(
            model_name='tgmchannel',
            name='categories_match',
            field=models.ManyToManyField(related_name='channel', to='tgm_channel.CategoriesMatch'),
        ),
    ]
