# Generated by Django 3.2.12 on 2022-07-16 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgm_channel', '0009_alter_tgmchannel_subs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tgmchannel',
            name='tgmlink',
            field=models.CharField(default='', max_length=255, unique=True, verbose_name='Cсылка на телеграмм'),
        ),
    ]
