# Generated by Django 3.2.12 on 2022-07-23 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgm_channel', '0010_alter_tgmchannel_tgmlink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tgmchannel',
            name='tgmlink',
            field=models.CharField(default='', error_messages={'unique': 'Данный канал уже есть на нашем сайте.'}, max_length=255, unique=True, verbose_name='Cсылка на телеграмм'),
        ),
    ]
